"""Pre-Draft Printable Cheat Sheet & Offline Backup Generator.

Generates CSV and clean printable Markdown/HTML cheat sheets for emergency
hard-copy draft backup.
"""

from __future__ import annotations

import csv
import io
from typing import Any, Dict, List, Sequence


def generate_csv_cheat_sheet(players: Sequence[Dict[str, Any]]) -> str:
    """Generate a clean CSV cheat sheet string of all available players."""
    output = io.StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow([
        "Rank/Tier",
        "Position",
        "Full Name",
        "Team",
        "Bye Week",
        "ADP",
        "Median Proj",
        "Floor Proj",
        "Ceiling Proj",
        "Depth Role",
        "Handcuff For",
    ])

    sorted_players = sorted(
        players,
        key=lambda x: (
            str(x.get("position")),
            int(x.get("tier", 99)),
            -float(x.get("projection_median") or 0.0),
        ),
    )

    for p in sorted_players:
        writer.writerow([
            p.get("tier", ""),
            p.get("position", ""),
            p.get("full_name", ""),
            p.get("team", ""),
            p.get("bye_week", ""),
            p.get("adp", ""),
            p.get("projection_median", ""),
            p.get("projection_floor", ""),
            p.get("projection_ceiling", ""),
            p.get("depth_role", ""),
            p.get("handcuff_for_player_id", ""),
        ])

    return output.getvalue()


def generate_printable_html_cheat_sheet(
    players: Sequence[Dict[str, Any]], league_title: str = "Fantasy Football Pre-Draft Cheat Sheet"
) -> str:
    """Generate a print-ready HTML cheat sheet document grouped by position and tier."""
    positions = ["QB", "RB", "WR", "TE", "K", "DST"]

    html_lines = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        f"<title>{league_title}</title>",
        "<style>",
        "  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 20px; color: #111; }",
        "  h1 { text-align: center; font-size: 24px; margin-bottom: 5px; }",
        "  p.subtitle { text-align: center; color: #555; margin-top: 0; font-size: 13px; }",
        "  .grid { display: flex; flex-wrap: wrap; gap: 15px; }",
        "  .col { flex: 1; min-width: 280px; }",
        "  h2 { background: #1e293b; color: white; padding: 6px 10px; font-size: 15px; border-radius: 4px; margin-top: 15px; margin-bottom: 8px; }",
        "  table { width: 100%; border-collapse: collapse; font-size: 11px; margin-bottom: 15px; }",
        "  th { background: #f1f5f9; text-align: left; padding: 4px 6px; border-bottom: 2px solid #cbd5e1; }",
        "  td { padding: 4px 6px; border-bottom: 1px solid #e2e8f0; }",
        "  .tier-header { background: #e2e8f0; font-weight: bold; font-size: 11px; }",
        "  @media print { body { margin: 0; } button { display: none; } }",
        "</style>",
        "</head>",
        "<body>",
        f"<h1>🏈 {league_title}</h1>",
        "<p class='subtitle'>Official Pre-Draft Cheat Sheet Backup | Generated by The Best Damn Fantasy Football Drafting App</p>",
        "<div style='text-align: center; margin-bottom: 15px;'>",
        "  <button onclick='window.print()' style='padding: 8px 16px; background: #2563eb; color: white; border: none; border-radius: 4px; font-weight: bold; cursor: pointer;'>🖨️ Print Cheat Sheet (Ctrl+P / PDF)</button>",
        "</div>",
        "<div class='grid'>",
    ]

    for pos in positions:
        pos_players = [
            p for p in players
            if str(p.get("position", "")).upper() == pos and p.get("is_available", True)
        ]

        if not pos_players:
            continue

        pos_players_sorted = sorted(
            pos_players,
            key=lambda x: (
                int(x.get("tier", 99)),
                -float(x.get("projection_median") or 0.0),
                float(x.get("adp") if x.get("adp") is not None else 999.0),
            ),
        )

        html_lines.append(f"<div class='col'>")
        html_lines.append(f"<h2>{pos} - Top Candidates</h2>")
        html_lines.append("<table>")
        html_lines.append("<tr><th>Tier</th><th>Player Name</th><th>Team</th><th>Bye</th><th>ADP</th><th>Proj</th></tr>")

        current_tier = None
        for p in pos_players_sorted[:40]:  # Top 40 per position
            tier = int(p.get("tier", 99))
            if current_tier != tier:
                current_tier = tier
                html_lines.append(f"<tr class='tier-header'><td colspan='6'>Tier {tier}</td></tr>")

            name = p.get("full_name", "")
            team = p.get("team", "FA")
            bye = p.get("bye_week") or "-"
            adp = p.get("adp") or "-"
            median = p.get("projection_median") or 0.0

            html_lines.append(
                f"<tr>"
                f"<td>T{tier}</td>"
                f"<td><strong>{name}</strong></td>"
                f"<td>{team}</td>"
                f"<td>{bye}</td>"
                f"<td>{adp}</td>"
                f"<td>{median}</td>"
                f"</tr>"
            )

        html_lines.append("</table>")
        html_lines.append("</div>")

    html_lines.extend(["</div>", "</body>", "</html>"])
    return "\n".join(html_lines)


def generate_ranked_csv_cheat_sheet(ranked_players: Sequence[Dict[str, Any]]) -> str:
    """Generate a clean CSV cheat sheet string of Ada-ranked players."""
    output = io.StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow([
        "Overall Rank",
        "Player Name",
        "Position",
        "Team",
        "Bye Week",
        "ADP",
        "Composite Score",
        "VOR Raw",
        "Value Gap vs ADP",
        "Tier",
        "Median Proj",
    ])

    for p in ranked_players:
        writer.writerow([
            p.get("rank", ""),
            p.get("player_name", p.get("full_name", "")),
            p.get("position", ""),
            p.get("team", ""),
            p.get("bye_week", ""),
            p.get("adp", ""),
            p.get("composite_score", ""),
            p.get("breakdown", {}).get("vor_raw", ""),
            p.get("value_gap", ""),
            p.get("tier", ""),
            p.get("projection_median", ""),
        ])

    return output.getvalue()


def generate_ranked_html_cheat_sheet(
    ranked_players: Sequence[Dict[str, Any]],
    league_title: str = "Fantasy Football Ada-Ranked Cheat Sheet",
) -> str:
    """Generate a print-ready HTML cheat sheet document sorted by Ada Composite Rank."""
    html_lines = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        f"<title>{league_title}</title>",
        "<style>",
        "  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 20px; color: #111; }",
        "  h1 { text-align: center; font-size: 24px; margin-bottom: 5px; }",
        "  p.subtitle { text-align: center; color: #555; margin-top: 0; font-size: 13px; }",
        "  table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 15px; }",
        "  th { background: #1e293b; color: white; text-align: left; padding: 6px 8px; font-size: 12px; }",
        "  td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; }",
        "  tr:nth-child(even) { background: #f8fafc; }",
        "  .pos-QB { color: #1d4ed8; font-weight: bold; }",
        "  .pos-RB { color: #15803d; font-weight: bold; }",
        "  .pos-WR { color: #c2410c; font-weight: bold; }",
        "  .pos-TE { color: #7e22ce; font-weight: bold; }",
        "  .pos-K { color: #475569; }",
        "  .pos-DST { color: #0369a1; }",
        "  .steal { color: #15803d; font-weight: bold; }",
        "  @media print { body { margin: 0; } button { display: none; } }",
        "</style>",
        "</head>",
        "<body>",
        f"<h1>🤖 {league_title}</h1>",
        "<p class='subtitle'>Official Quant Engine Master Ranking | Powered by Ada Composite Score</p>",
        "<div style='text-align: center; margin-bottom: 15px;'>",
        "  <button onclick='window.print()' style='padding: 8px 16px; background: #2563eb; color: white; border: none; border-radius: 4px; font-weight: bold; cursor: pointer;'>🖨️ Print Ranked Cheat Sheet (Ctrl+P / PDF)</button>",
        "</div>",
        "<table>",
        "<tr><th>Rank</th><th>Player Name</th><th>Pos</th><th>Team</th><th>Bye</th><th>ADP</th><th>Composite</th><th>VOR</th><th>Value Gap</th><th>Tier</th><th>Proj</th></tr>",
    ]

    for p in ranked_players[:150]:  # Top 150 overall
        rank = p.get("rank", "")
        name = p.get("player_name", p.get("full_name", ""))
        pos = p.get("position", "")
        team = p.get("team", "FA")
        bye = p.get("bye_week") or "-"
        adp = p.get("adp") or "-"
        comp = f"{p.get('composite_score', 0.0):.4f}"
        vor = p.get("breakdown", {}).get("vor_raw", "-")
        gap = p.get("value_gap", 0.0)
        gap_str = f"+{gap:.0f}" if gap > 0 else f"{gap:.0f}"
        tier = p.get("tier", 99)
        median = p.get("projection_median", 0.0)

        html_lines.append(
            f"<tr>"
            f"<td><strong>#{rank}</strong></td>"
            f"<td><strong>{name}</strong></td>"
            f"<td class='pos-{pos}'>{pos}</td>"
            f"<td>{team}</td>"
            f"<td>{bye}</td>"
            f"<td>{adp}</td>"
            f"<td><strong>{comp}</strong></td>"
            f"<td>{vor}</td>"
            f"<td class='{'steal' if gap >= 8 else ''}'>{gap_str}</td>"
            f"<td>T{tier}</td>"
            f"<td>{median}</td>"
            f"</tr>"
        )

    html_lines.extend(["</table>", "</body>", "</html>"])
    return "\n".join(html_lines)
